name: Build images

on:
  push:
    branches: [master]

jobs:
  build-push-images:
    name: Build and publish image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.KEY_GITHUB }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # Wpis ghcr.io odpowiada za wysyłanie obrazu do rejestru GitHuba
          tags: |
            ghcr.io/dawdrz/zad1
            dawiddrzew/zad1
          cache-from: type=registry,ref=dawiddrzew/z1:buildcache
          cache-to: type=registry,ref=dawiddrzew/z1:buildcache,mode=max
          platforms: linux/arm64/v8,linux/amd64
          context: .
          file: ./Dockerfile
          push: true
